export = Object.freeze({
    BUYER_ORDER_STATUS: {
        ADVANCED_PAYMENT: "ADVANCED_PAYMENT",
        MANUFACTURING: "MANUFACTURING",
        PACKING: "PACKING",
        INSPECTION: "INSPECTION",
        SHIPPING: "SHIPPING",
        TRANSACTION_COMPLETED: "TRANSACTION_COMPLETED",
    },
    BUYER_ORDER_STATUS_ARRAY: ["ADVANCED_PAYMENT", "MANUFACTURING", "PACKING", "INSPECTION", "SHIPPING", "TRANSACTION_COMPLETED"],
    VENDOR_ORDER_STATUS: {
        ORDER: "ORDER",
        ADVANCED_PAYMENT: "ADVANCED_PAYMENT",
        MANUFACTURING: "MANUFACTURING",
        PACKING: "PACKING",
        INSPECTION: "INSPECTION",
        DELIVERED: "DELIVERED",
        COMPLETED: "COMPLETED",
    },
    VENDOR_ORDER_STATUS_ARRAY: ["ORDER", "ADVANCED_PAYMENT", "MANUFACTURING", "PACKING", "INSPECTION", "DELIVERED", "COMPLETED"],

    IMAGES_TYPE: {
        SAMPLE: "SAMPLE",
        FIRST_PRODUCT: "FIRST_PRODUCT",
        ROW_MATERIAL: "ROW_MATERIAL",
        MANUFACTURING: "MANUFACTURING",
        PACKING: "PACKING",
        DOCUMENTATION: "DOCMENTATION"
    },

    ORDER_TYPE: {
        ON_GONING_ORDER: "ON_GONING_ORDER",
        UP_COMING_ORDER: "UP_COMING_ORDER",
        SHIPPED_ORDER: "SHIPPED_ORDER",
        DELIVERED_ORDER: "DELIVERED_ORDER"
    }



});